### ISSUE TITLE
Broken package update scanner

### ISSUE THREAD

**Issue by fingolfin** [gap-system/PackageDistro#724]
The package update scanner is broken. This is the error:
```
update packages/examplesforhomalg/meta.json
Traceback (most recent call last):
  File "tools/scan_for_updates.py", line 140, in <module>
    main([normalize_pkg_name(x) for x in sys.argv[1:]])
  File "tools/scan_for_updates.py", line 136, in main
    import_packages(updated_pkgs)
  File "tools/scan_for_updates.py", line 114, in import_packages
    utils.download(url, archive_fname)
  File "/home/runner/work/PackageDistro/PackageDistro/tools/utils.py", line 54, in download
    response.raise_for_status()  # raise a meaningful (?) exception if there was e.g. a 404 error
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://github.com/gap-packages/francy/releases/download/v2.0.0/francy-2.0.0.tar.gz
```

So it seems something is wrong with Francy 2.0.0 (namely its release is missing the required tarballs -- CC @mcmartins). But regardless of that, of course this should not cause the scanner to fail! This must be fixed.

**Comment by fingolfin** [comment]
Resolved by PR #725
